name: Android Debug Build & Firebase Distribution

on:
  push:
    branches:
      - main
      - develop
      - master
      - feature/*

jobs:
  build:
    name: Build & Distribute Debug APK
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2️⃣ Setup JDK
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      # 3️⃣ Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x ./gradlew    

      # 4️⃣ Setup Gradle cache
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # 5️⃣ Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # 6️⃣ Upload Artifact to GitHub (Optional)
      - name: Upload Debug APK to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # 7️⃣ Download artifact for Firebase upload
      - name: Download Debug APK artifact
        uses: actions/download-artifact@v4
        with:
          name: app-debug-apk
          path: ./release

      # 8️⃣ Verify artifact
      - name: List release folder
        run: ls -la ./release

      # 9️⃣ Upload to Firebase App Distribution (with debug logs)
      - name: Distribute Debug APK to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: 1:680561170660:android:b317c1be177ffa6a7274f1
          serviceCredentialsFileContent: ${{ secrets.SERVICE_ACCOUNT }}
          file: ./release/app-debug.apk
          groups: qa-testers
          releaseNotes: "New *Debug* build from GitHub CI 🚀"
          debug: true
